include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Treat all warnings and info as allowed (won't break CI or count as issues)
    unused_import: ignore
    dead_code: ignore
    missing_return: ignore
    unused_local_variable: ignore

linter:
  rules:
    # Optionally disable specific lint rules
    - avoid_print
    - prefer_const_constructors
