arb-dir: lib/l10n
template-arb-file: intl_en.arb
output-localization-file: app_localizations.dart
output-class: S
preferred-supported-locales:
  - en
  - ms
  - zh
  - zh_TW

flutter:
  generate: true
  uses-material-design: true
