name: invoice_scanner
description: "Invoice Scanner App"

version: 1.2.0+3

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  google_mlkit_text_recognition: ^0.15.0
  google_mlkit_commons: ^0.11.0
  path_provider: ^2.1.2
  path: ^1.9.0
  provider: ^6.1.2
  http: ^1.2.1
  google_sign_in: ^6.1.4
  googleapis: ^12.0.0
  googleapis_auth: ^1.4.1
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  webview_flutter: ^4.2.2
  url_launcher: ^6.1.10
  flutter_plugin_android_lifecycle: ^2.0.15
  flutter_localization: ^0.3.3
  fl_chart: ^0.66.0
  file_picker: ^10.2.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
