// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKkoyZ0Yu7d74HjEiaxuxFDvilxuTx7W8',
    appId: '1:563142801704:web:b526270ab76e8cb8d1781d',
    messagingSenderId: '563142801704',
    projectId: 'invoice-manager-0000',
    authDomain: 'invoice-manager-0000.firebaseapp.com',
    storageBucket: 'invoice-manager-0000.firebasestorage.app',
    measurementId: 'G-4R4VJHESCL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDKCvYaP2oY8V_KDwV-4_zRDia8Asy82w',
    appId: '1:563142801704:android:3273e544984119c8d1781d',
    messagingSenderId: '563142801704',
    projectId: 'invoice-manager-0000',
    storageBucket: 'invoice-manager-0000.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNwfbp9mvffkom0DhPd1F3MS1385Ic39E',
    appId: '1:563142801704:ios:f7d9d50828001228d1781d',
    messagingSenderId: '563142801704',
    projectId: 'invoice-manager-0000',
    storageBucket: 'invoice-manager-0000.firebasestorage.app',
    iosBundleId: 'com.example.invoiceScanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNwfbp9mvffkom0DhPd1F3MS1385Ic39E',
    appId: '1:563142801704:ios:f7d9d50828001228d1781d',
    messagingSenderId: '563142801704',
    projectId: 'invoice-manager-0000',
    storageBucket: 'invoice-manager-0000.firebasestorage.app',
    iosBundleId: 'com.example.invoiceScanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKkoyZ0Yu7d74HjEiaxuxFDvilxuTx7W8',
    appId: '1:563142801704:web:484a31f01a7b5126d1781d',
    messagingSenderId: '563142801704',
    projectId: 'invoice-manager-0000',
    authDomain: 'invoice-manager-0000.firebaseapp.com',
    storageBucket: 'invoice-manager-0000.firebasestorage.app',
    measurementId: 'G-49DWP4N770',
  );
}
